// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nova.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nova.Api.Migrations
{
    [DbContext(typeof(NovaDbContext))]
    [Migration("20260923151628_AddAdminEntities")]
    partial class AddAdminEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nova.Api.Entities.AIChatSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("PackageId")
                        .HasColumnType("text")
                        .HasColumnName("package_id");

                    b.Property<int>("QueryCount")
                        .HasColumnType("integer")
                        .HasColumnName("query_count");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ai_chat_sessions");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("ix_ai_chat_sessions_package_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ai_chat_sessions_user_id");

                    b.ToTable("ai_chat_sessions", (string)null);
                });

            modelBuilder.Entity("Nova.Api.Entities.AIPhotoQuery", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination_name");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<DateTime>("QueryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("query_date");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ai_photo_queries");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ai_photo_queries_user_id");

                    b.ToTable("ai_photo_queries", (string)null);
                });

            modelBuilder.Entity("Nova.Api.Entities.Activity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("interval")
                        .HasColumnName("closing_time");

                    b.Property<decimal>("CostPerPerson")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_per_person");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DestinationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination_id");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("interval")
                        .HasColumnName("opening_time");

                    b.HasKey("Id")
                        .HasName("pk_activities");

                    b.HasIndex("DestinationId")
                        .HasDatabaseName("ix_activities_destination_id");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("Nova.Api.Entities.Booking", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booking_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_name");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TripId")
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_bookings_trip_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_bookings_user_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Nova.Api.Entities.BusRoute", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ArrivalTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arrival_time");

                    b.Property<string>("BusNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bus_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DepartureTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("departure_time");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<decimal>("Fare")
                        .HasColumnType("numeric")
                        .HasColumnName("fare");

                    b.Property<string>("OperatingDays")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operating_days");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_bus_routes");

                    b.ToTable("bus_routes", (string)null);
                });

            modelBuilder.Entity("Nova.Api.Entities.ChatbotPackage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<bool>("IncludesPhotoQueries")
                        .HasColumnType("boolean")
                        .HasColumnName("includes_photo_queries");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("QuestionLimit")
                        .HasColumnType("integer")
                        .HasColumnName("question_limit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_chatbot_packages");

                    b.ToTable("chatbot_packages", (string)null);
                });

            modelBuilder.Entity("Nova.Api.Entities.ChatbotPackagePurchase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<int>("RemainingQueries")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_queries");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chatbot_package_purchases");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("ix_chatbot_package_purchases_package_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chatbot_package_purchases_user_id");

                    b.ToTable("chatbot_package_purchases", (string)null);
                });

            modelBuilder.Entity("Nova.Api.Entities.Destination", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("province");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_destinations");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_destinations_slug");

                    b.ToTable("destinations", (string)null);
                });

            modelBuilder.Entity("Nova.Api.Entities.Itinerary", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalComments")
                        .HasColumnType("text")
                        .HasColumnName("approval_comments");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("approved_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("FeasibilityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("feasibility_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<decimal>("TotalEstimatedCost")
                        .HasColumnType("numeric")
                        .HasColumnName("total_estimated_cost");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_itineraries");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_itineraries_trip_id");

                    b.ToTable("itineraries", (string)null);
                });

            modelBuilder.Entity("Nova.Api.Entities.ItineraryApproval", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ApprovedByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("approved_by_user_id");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<string>("ItineraryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("itinerary_id");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_status");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("previous_status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_itinerary_approvals");

                    b.HasIndex("ItineraryId")
                        .HasDatabaseName("ix_itinerary_approvals_itinerary_id");

                    b.ToTable("itinerary_approvals", (string)null);
                });

            modelBuilder.Entity("Nova.Api.Entities.ItineraryDay", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("day_number");

                    b.Property<string>("ItineraryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("itinerary_id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_itinerary_days");

                    b.HasIndex("ItineraryId")
                        .HasDatabaseName("ix_itinerary_days_itinerary_id");

                    b.ToTable("itinerary_days", (string)null);
                });

            modelBuilder.Entity("Nova.Api.Entities.ItineraryGenerationWorkflow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConstraintsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("constraints_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_step");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_itinerary_generation_workflows");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_itinerary_generation_workflows_trip_id");

                    b.ToTable("itinerary_generation_workflows", (string)null);
                });

            modelBuilder.Entity("Nova.Api.Entities.ItineraryItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ActivityId")
                        .HasColumnType("text")
                        .HasColumnName("activity_id");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activity_name");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_cost");

                    b.Property<string>("ItineraryDayId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("itinerary_day_id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_order");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.Property<int>("TravelTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("travel_time_minutes");

                    b.HasKey("Id")
                        .HasName("pk_itinerary_items");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("ix_itinerary_items_activity_id");

                    b.HasIndex("ItineraryDayId")
                        .HasDatabaseName("ix_itinerary_items_itinerary_day_id");

                    b.ToTable("itinerary_items", (string)null);
                });

            modelBuilder.Entity("Nova.Api.Entities.PromoCode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_value");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Partner")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partner");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("TimesUsed")
                        .HasColumnType("integer")
                        .HasColumnName("times_used");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("integer")
                        .HasColumnName("usage_limit");

                    b.HasKey("Id")
                        .HasName("pk_promo_codes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_promo_codes_code");

                    b.ToTable("promo_codes", (string)null);
                });

            modelBuilder.Entity("Nova.Api.Entities.PromoCodeUsage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal>("DiscountApplied")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_applied");

                    b.Property<string>("PromoCodeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("promo_code_id");

                    b.Property<string>("TripId")
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_promo_code_usages");

                    b.HasIndex("PromoCodeId")
                        .HasDatabaseName("ix_promo_code_usages_promo_code_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_promo_code_usages_user_id");

                    b.ToTable("promo_code_usages", (string)null);
                });

            modelBuilder.Entity("Nova.Api.Entities.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DestinationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("SentimentLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sentiment_label");

                    b.Property<double>("SentimentScore")
                        .HasColumnType("double precision")
                        .HasColumnName("sentiment_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("DestinationId")
                        .HasDatabaseName("ix_reviews_destination_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reviews_user_id");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("Nova.Api.Entities.TrainSchedule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ArrivalTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arrival_time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DepartureTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("departure_time");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<decimal>("Fare")
                        .HasColumnType("numeric")
                        .HasColumnName("fare");

                    b.Property<string>("OperatingDays")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operating_days");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TrainName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("train_name");

                    b.Property<string>("TrainNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("train_number");

                    b.Property<string>("TrainType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("train_type");

                    b.HasKey("Id")
                        .HasName("pk_train_schedules");

                    b.ToTable("train_schedules", (string)null);
                });

            modelBuilder.Entity("Nova.Api.Entities.TransportOption", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ArrivalStation")
                        .HasColumnType("text")
                        .HasColumnName("arrival_station");

                    b.Property<string>("ArrivalTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arrival_time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DepartureStation")
                        .HasColumnType("text")
                        .HasColumnName("departure_station");

                    b.Property<string>("DepartureTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("departure_time");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("Direction")
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<decimal?>("EstimatedFare")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_fare");

                    b.Property<List<string>>("IntermediateStops")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("intermediate_stops");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_selected");

                    b.Property<string>("ItineraryItemId")
                        .HasColumnType("text")
                        .HasColumnName("itinerary_item_id");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<string>("RouteName")
                        .HasColumnType("text")
                        .HasColumnName("route_name");

                    b.Property<string>("RouteNumber")
                        .HasColumnType("text")
                        .HasColumnName("route_number");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("TrainName")
                        .HasColumnType("text")
                        .HasColumnName("train_name");

                    b.Property<string>("TrainNumber")
                        .HasColumnType("text")
                        .HasColumnName("train_number");

                    b.Property<string>("TrainType")
                        .HasColumnType("text")
                        .HasColumnName("train_type");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transport_type");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("travel_date");

                    b.Property<string>("TripId")
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("pk_transport_options");

                    b.HasIndex("ItineraryItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_transport_options_itinerary_item_id");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_transport_options_trip_id");

                    b.HasIndex("Origin", "Destination", "TravelDate")
                        .HasDatabaseName("ix_transport_options_origin_destination_travel_date");

                    b.ToTable("transport_options", (string)null);
                });

            modelBuilder.Entity("Nova.Api.Entities.Trip", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal>("Budget")
                        .HasColumnType("numeric")
                        .HasColumnName("budget");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("DestinationId")
                        .HasColumnType("text")
                        .HasColumnName("destination_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<List<string>>("Interests")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("interests");

                    b.Property<int>("NumberOfTravelers")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_travelers");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TripStyle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trip_style");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_trips");

                    b.HasIndex("DestinationId")
                        .HasDatabaseName("ix_trips_destination_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_trips_user_id");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("Nova.Api.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Nova.Api.Entities.WorkflowAuditLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_audit_logs");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("ix_workflow_audit_logs_workflow_id");

                    b.ToTable("workflow_audit_logs", (string)null);
                });

            modelBuilder.Entity("Nova.Api.Entities.AIChatSession", b =>
                {
                    b.HasOne("Nova.Api.Entities.ChatbotPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .HasConstraintName("fk_ai_chat_sessions_chatbot_packages_package_id");

                    b.HasOne("Nova.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_chat_sessions_users_user_id");

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nova.Api.Entities.AIPhotoQuery", b =>
                {
                    b.HasOne("Nova.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_photo_queries_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nova.Api.Entities.Activity", b =>
                {
                    b.HasOne("Nova.Api.Entities.Destination", "Destination")
                        .WithMany("Activities")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activities_destinations_destination_id");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Nova.Api.Entities.Booking", b =>
                {
                    b.HasOne("Nova.Api.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .HasConstraintName("fk_bookings_trips_trip_id");

                    b.HasOne("Nova.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_users_user_id");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nova.Api.Entities.ChatbotPackagePurchase", b =>
                {
                    b.HasOne("Nova.Api.Entities.ChatbotPackage", "Package")
                        .WithMany("Purchases")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chatbot_package_purchases_chatbot_packages_package_id");

                    b.HasOne("Nova.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chatbot_package_purchases_users_user_id");

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nova.Api.Entities.Itinerary", b =>
                {
                    b.HasOne("Nova.Api.Entities.Trip", "Trip")
                        .WithMany("Itineraries")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itineraries_trips_trip_id");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Nova.Api.Entities.ItineraryApproval", b =>
                {
                    b.HasOne("Nova.Api.Entities.Itinerary", "Itinerary")
                        .WithMany("Approvals")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itinerary_approvals_itineraries_itinerary_id");

                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("Nova.Api.Entities.ItineraryDay", b =>
                {
                    b.HasOne("Nova.Api.Entities.Itinerary", "Itinerary")
                        .WithMany("Days")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itinerary_days_itineraries_itinerary_id");

                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("Nova.Api.Entities.ItineraryGenerationWorkflow", b =>
                {
                    b.HasOne("Nova.Api.Entities.Trip", "Trip")
                        .WithMany("Workflows")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itinerary_generation_workflows_trips_trip_id");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Nova.Api.Entities.ItineraryItem", b =>
                {
                    b.HasOne("Nova.Api.Entities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .HasConstraintName("fk_itinerary_items_activities_activity_id");

                    b.HasOne("Nova.Api.Entities.ItineraryDay", "ItineraryDay")
                        .WithMany("Items")
                        .HasForeignKey("ItineraryDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itinerary_items_itinerary_days_itinerary_day_id");

                    b.Navigation("Activity");

                    b.Navigation("ItineraryDay");
                });

            modelBuilder.Entity("Nova.Api.Entities.PromoCodeUsage", b =>
                {
                    b.HasOne("Nova.Api.Entities.PromoCode", "PromoCode")
                        .WithMany("Usages")
                        .HasForeignKey("PromoCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promo_code_usages_promo_codes_promo_code_id");

                    b.HasOne("Nova.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promo_code_usages_users_user_id");

                    b.Navigation("PromoCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nova.Api.Entities.Review", b =>
                {
                    b.HasOne("Nova.Api.Entities.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_destinations_destination_id");

                    b.HasOne("Nova.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_users_user_id");

                    b.Navigation("Destination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nova.Api.Entities.TransportOption", b =>
                {
                    b.HasOne("Nova.Api.Entities.ItineraryItem", "ItineraryItem")
                        .WithOne("SelectedTransport")
                        .HasForeignKey("Nova.Api.Entities.TransportOption", "ItineraryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_transport_options_itinerary_items_itinerary_item_id");

                    b.HasOne("Nova.Api.Entities.Trip", "Trip")
                        .WithMany("TransportOptions")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_transport_options_trips_trip_id");

                    b.Navigation("ItineraryItem");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Nova.Api.Entities.Trip", b =>
                {
                    b.HasOne("Nova.Api.Entities.Destination", "DestinationEntity")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .HasConstraintName("fk_trips_destinations_destination_id");

                    b.HasOne("Nova.Api.Entities.User", "User")
                        .WithMany("Trips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trips_users_user_id");

                    b.Navigation("DestinationEntity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nova.Api.Entities.WorkflowAuditLog", b =>
                {
                    b.HasOne("Nova.Api.Entities.ItineraryGenerationWorkflow", "Workflow")
                        .WithMany("AuditLogs")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_audit_logs_itinerary_generation_workflows_workflow");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Nova.Api.Entities.ChatbotPackage", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("Nova.Api.Entities.Destination", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Nova.Api.Entities.Itinerary", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Days");
                });

            modelBuilder.Entity("Nova.Api.Entities.ItineraryDay", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Nova.Api.Entities.ItineraryGenerationWorkflow", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("Nova.Api.Entities.ItineraryItem", b =>
                {
                    b.Navigation("SelectedTransport");
                });

            modelBuilder.Entity("Nova.Api.Entities.PromoCode", b =>
                {
                    b.Navigation("Usages");
                });

            modelBuilder.Entity("Nova.Api.Entities.Trip", b =>
                {
                    b.Navigation("Itineraries");

                    b.Navigation("TransportOptions");

                    b.Navigation("Workflows");
                });

            modelBuilder.Entity("Nova.Api.Entities.User", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
